# Generated by Django 3.2.8 on 2021-10-11 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graduated', models.PositiveSmallIntegerField()),
                ('school_name', models.CharField(max_length=255)),
                ('course_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('certificate', models.ImageField(blank=True, upload_to='')),
                ('slug', models.SlugField(max_length=255, unique='course_name')),
            ],
        ),
    ]
