# Generated by Django 3.2.8 on 2021-10-12 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.PositiveSmallIntegerField()),
                ('end_date', models.PositiveSmallIntegerField()),
                ('company_name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('industry', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(max_length=255, unique='company_name')),
            ],
        ),
    ]
