# Generated by Django 3.2.8 on 2021-10-13 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basis', '0004_auto_20211013_2112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='email',
            new_name='sender_email',
        ),
    ]
