# Generated by Django 3.2.8 on 2021-10-16 08:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('basis', '0008_alter_uploaddocument_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('link', models.URLField(blank=True)),
                ('slug', models.SlugField(max_length=255, unique='project_name')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
