# Generated by Django 3.2.8 on 2021-10-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basis', '0010_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mailing',
            field=models.BooleanField(default=False),
        ),
    ]
