# Generated by Django 3.2.8 on 2021-10-19 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basis', '0012_auto_20211019_1443'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
        migrations.RenameField(
            model_name='messages',
            old_name='message',
            new_name='text_message',
        ),
    ]
