# Generated by Django 3.2.8 on 2021-10-19 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basis', '0013_auto_20211019_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=300)),
                ('news_link', models.URLField()),
                ('news_data', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=300, unique='news_title')),
            ],
        ),
    ]
