# Generated by Django 3.2.8 on 2021-10-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basis', '0014_news'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='news_data',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='news_title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='news',
            name='news_link',
        ),
        migrations.AddField(
            model_name='news',
            name='body',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='news',
            name='link',
            field=models.TextField(default=''),
        ),
    ]
