# Generated by Django 3.2.8 on 2021-10-19 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basis', '0015_auto_20211019_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='slug',
        ),
    ]
