# Generated by Django 3.2.8 on 2021-10-19 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basis', '0016_remove_news_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
        migrations.RenameField(
            model_name='messages',
            old_name='text_message',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='mailing',
        ),
        migrations.AlterField(
            model_name='profile',
            name='hr',
            field=models.BooleanField(default=False),
        ),
    ]
