# Generated by Django 3.2.8 on 2021-10-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basis', '0020_auto_20211020_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topnews',
            name='slug',
            field=models.SlugField(default='', max_length=300, unique='title'),
        ),
    ]
