# Generated by Django 3.2.8 on 2021-10-22 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basis', '0021_alter_topnews_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='subscribed_for_mailings',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='subscription_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
