# Generated by Django 3.2.8 on 2021-10-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basis', '0022_auto_20211022_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
